version: '2'

services:
    wildflyswarm:
      build: .
      ports:
        - "8080:8080"
      external_links:
        - postgresdb:postgres
networks:
  default:
    external:
      name: postgresdb_default